SOURCES :=	src/camera.c \
	src/collisions/cylinder.c \
	src/collisions/plane.c \
	src/collisions/sphere.c \
	src/colors/color_basics.c \
	src/colors/color_debug.c \
	src/colors/color_math.c \
	src/lights/light.c \
	src/log.c \
	src/mat4.c \
	src/parse/atod.c \
	src/parse/color.c \
	src/parse/objects.c \
	src/parse/parse.c \
	src/parse/vector.c \
	src/program/program_init.c \
	src/program/scene_draw.c \
	src/ray/ray3.c \
	src/ray/ray3_debug.c \
	src/raycasting.c \
	src/shapes/shape.c \
	src/shapes/shape_debug.c \
	src/shapes/shape_mask.c \
	src/shapes/shape_material.c \
	src/shapes/shape_plane.c \
	src/vec3/vec3_basics.c \
	src/vec3/vec3_debug.c \
	src/vec3/vec3_math.c \
